#
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
#
# go to sleep after 15 minutes (1*60*15*1000ms)

CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

CONFIG_ZMK_SLEEP=y





CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=160
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# Uncomment the following line to enable NKRO
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Some operating systems have problems with full support for consumer keycodes.
# Uncomment the following line if keycodes labeled "consumer" like C_AC_SEARCH don't work
#CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Mouse enable
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_BACKLIGHT_BRT_START=100
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8
